### ISSUE TITLE
fix(actions): Terraform Plan formatting

### ISSUE THREAD

**Issue by HarryET** [WalletConnect/CloudSIWE#21]
Formatting is weird, look at other repos to try and fix.

## Example
![image](https://user-images.githubusercontent.com/29015545/178998734-e7079e35-6ca2-4828-a64f-f4f77c27bd56.png)

**Comment by JonathanConn** [comment]
Could the file being passed in by wrong? [snippit](https://github.com/WalletConnect/CloudSIWE/blob/6633b5c46756f3001b7a922ff75e203a43cd1524/.github/workflows/terraform_ci.yml#L38-L49)
`PLAN` is using `steps.plan.outputs.plan` but there is `plan.tfplan` and `plan.txt`

**Comment by HarryET** [comment]
All this infra will be torn down soon, this shouldn't be a focus
