### ISSUE TITLE
SIWE launch

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/CloudSIWE#33]
Launch list of issues.

Critical:
- [x] https://github.com/WalletConnect/cloud-app/issues/141
- [x] https://github.com/WalletConnect/CloudSIWE/issues/31
- [x] https://github.com/WalletConnect/cloud-app/issues/137
- [x] https://github.com/WalletConnect/cloud-app/issues/140
- [x] https://github.com/WalletConnect/cloud-app/issues/139
- [x] #34 
- [x] Fix emails
- [ ] Final manual testing on different devices and wallets

**Comment by HarryET** [comment]
Planned for Monday

**Comment by HarryET** [comment]
Live on https://cloud.walletconnect.com
