### ISSUE TITLE
Implement CAIP-10 for addresses instead of struct

### ISSUE THREAD

**Issue by etodanik** [WalletConnect/CloudSIWE#38]
Just skimming your PR over at https://github.com/supabase/gotrue/pull/282 and since I have no comment ability there, I'd love to contribute a few comments here (since this is kind of the "nerve center" for the temporary self-hosted solution?).

I think that on a DB level, the PR creates a lot of unnecessary new tables (kind of rhyming with @hf feedback there. Would you consider using something like this to identify chains in the `provider` field? 
https://chainagnostic.org/CAIPs/caip-2

It could then be prefixed with a `web3:` prefix as per @hf recommendation. e.g:
`web3:eip155:1`

Or you can just go raw and write:
`eip155:1` (This seems cleaner and I don't see how it would be a problem, since it won't conceivably clash with any other provider in gotrue)

Then you eliminate all crypto specific identity tables and you can store the other information (such as address e.t.c) in the `identity_data` JSONB field.

As for the SIWE logic, it would be useful to already write `SIWx` (CAIP-122: https://chainagnostic.org/CAIPs/caip-122), since it's already a superset of EIP-4361 (SIWE) abstracted for chain agnostic use.

I'd be happy to contribute code directly (as well as a migration strategy for your existing stuff) since I'm working on a similar solution and would love to contribute to existing efforts vs. forking effort.

**Comment by HarryET** [comment]
Hi, sorry this was missed. Supabase decided to close the PR and we have migrated away from it internally.
